export { reducer } from './reducer'
export { control, completions, scores } from './control'
export { initialState } from './state'
export { encode, encodeInto, erectionId, featureSpec, FEATURE_LEN } from './encode'
export type { FeatureSpec } from './encode'
export { parseResourceParam } from './board/resource'

// runtime enums (values), needed by consumers that branch on game state
export { GameStatusEnum } from './types'
export { GameCommandEnum } from './types'
export { PlayerColor } from './types'
export { ResourceEnum } from './types'

export type { Controls } from './types'
export type { Score } from './types'
export type { Cost } from './types'
export type { GameConfigPlayers } from './types'
export type { GameConfigLength } from './types'
export type { GameConfigCountry } from './types'
export type { GameCommandConfigParams } from './types'
export type { GameCommandStartParams } from './types'
export type { ErectionEnum } from './types'
export type { SettlementCost } from './types'
export type { Tile } from './types'
export type { Tableau } from './types'
export type { Rondel } from './types'
export type { Frame } from './types'
export type { GameState } from './types'
export type { StateReducer } from './types'
