import { describe, it, expect } from '../testHelpers'
import { reducer } from '../reducer'
import { initialState } from '../state'
import { GameState } from '../types'
import { control } from '../control'
import { map, reduce, split } from 'ramda'

describe('game 2952eea3', () => {
  it('runs through a 4-player France long game', () => {
    const s0 = initialState
    const moves: string[][] = map(split(' '), [
      'CONFIG 4 france long',
      'START 74239 R G W B',
      'BUILD G12 3 0',
      'USE G12 ShPt',
      'COMMIT',
      'BUILD G07 3 0',
      'USE G07 Pt',
      'COMMIT',
      'BUILD G01 3 1',
      'USE G01',
      'USE G07 Pt',
      'COMMIT',
      'FELL_TREES 1 0',
      'COMMIT',
      'USE LG2 Gn',
      'COMMIT',
      'USE LW3',
      'BUY_PLOT -1 COAST',
      'COMMIT',
      'USE LR1',
      'COMMIT',
      'BUILD G02 3 1',
      'USE G02 PnClSh Wo',
      'COMMIT',
      'CUT_PEAT 0 0',
      'COMMIT',
      'FELL_TREES 1 0',
      'COMMIT',
      'BUY_DISTRICT 2 PLAINS',
      'BUILD G13 1 2',
      'COMMIT',
      'USE LB3',
      'COMMIT',
      'USE LG1',
      'COMMIT',
      'USE LW2 Gn',
      'COMMIT',
      'USE LR3 Jo',
      'COMMIT',
      'USE LB2 Sh',
      'COMMIT',
      'USE G12 GnGnGnPtPtPt',
      'COMMIT',
      'WORK_CONTRACT G13 Pn',
      'WITH_LAYBROTHER',
      'USE G13',
      'COMMIT',
      'BUILD F09 3 2',
      'USE F09',
      'USE G01',
      'USE G02 GnPnSh Wo',
      'COMMIT',
      'WORK_CONTRACT LG1 Pn',
      'WITH_LAYBROTHER',
      'USE LG1',
      'COMMIT',
      'BUILD F08 0 0',
      'COMMIT',
      'USE LW1',
      'COMMIT',
      'BUILD F10 2 2',
      'COMMIT',
      'USE G02 PtPnSh Cl',
      'COMMIT',
      'USE LG3',
      'BUY_PLOT -1 COAST',
      'COMMIT',
      'BUILD F04 -1 0',
      'USE F04 GnGnGnGn',
      'COMMIT',
      'USE LR2 Gn',
      'COMMIT',
      'USE LB3',
      'COMMIT',
      'FELL_TREES 1 0',
      'COMMIT',
      'CUT_PEAT 0 1',
      'COMMIT',
      'SETTLE SR1 3 0 GnWo',
      'COMMIT',
      'SETTLE SB2 3 0 ShShWoWoWo',
      'COMMIT',
      'SETTLE SG1 -1 0 PnWo',
      'COMMIT',
      'SETTLE SW1 -1 -1 FlCo',
      'COMMIT',
      'USE LR2 GnJo',
      'COMMIT',
      'USE G02 GnShWo Pn',
      'BUY_DISTRICT 2 HILLS',
      'COMMIT',
      'FELL_TREES 2 0',
      'COMMIT',
      'USE LW2 Sh',
      'COMMIT',
      'USE F09',
      'USE G01',
      'USE F04 GnGnGnGnGnGnGn',
      'COMMIT',
      'BUILD G18 3 2',
      'COMMIT',
      'USE LG2 Gn',
      'COMMIT',
      'USE LW1',
      'COMMIT',
      'WORK_CONTRACT F08 Pn',
      'WITH_LAYBROTHER',
      'USE F08 FlGnSwWo',
      'BUY_DISTRICT 3 HILLS',
      'COMMIT',
      'CUT_PEAT 0 2',
      'COMMIT',
      'USE G12 GnGnGnPnWoWo',
      'COMMIT',
      'BUILD F05 1 0',
      'USE F05 FlFlFlPtBrBr',
      'COMMIT',
      'BUILD F14 3 3',
      'USE F14 Jo',
      'COMMIT',
      'USE G18 ClClClPtPt',
      'COMMIT',
      'FELL_TREES 1 1',
      'COMMIT',
      'SETTLE SW2 3 1 ShShCo',
      'COMMIT',
      'SETTLE SR2 4 3 BrCo',
      'COMMIT',
      'SETTLE SB3 4 2 ShPnPnPnPnPn',
      'COMMIT',
      'COMMIT',
      'USE LW1',
      'COMMIT',
      'USE G13 PnPn',
      'COMMIT',
      'USE G02 PtClCe Gn',
      'COMMIT',
      'BUILD F11 -1 -1',
      'USE F11',
      'COMMIT',
      'WORK_CONTRACT G12 Pn',
      'USE G12 ShShShNiPtPtPt',
      'COMMIT',
      'USE F09',
      'USE F10 2 3',
    ])

    const sN = reduce<string[], GameState>((state, move) => reducer(state, move)!, s0, moves)
    expect(sN).toBeDefined()

    const c = control(sN, [])
    expect(c.completion).toContain('COMMIT')
  })
})
