import { describe, it, expect } from '../testHelpers'
import { reducer } from '../reducer'
import { initialState } from '../state'
import { GameState, GameStatePlaying } from '../types'
import { control } from '../control'
import { map, reduce, split } from 'ramda'

describe('game Claude4-1', () => {
  it('allows USE G26 after a WORK_CONTRACT G26 -> WITH_LAYBROTHER', () => {
    const s0 = initialState
    const moves: string[][] = map(split(' '), [
      'CONFIG 2 france long',
      'START 98369 R W',
      'BUILD G07 3 0',
      'USE G07 Pt',
      'COMMIT',
      'FELL_TREES 2 0',
      'COMMIT',
      'USE LR1',
      'COMMIT',
      'FELL_TREES 1 1 Jo',
      'COMMIT',
      'CUT_PEAT 0 1',
      'COMMIT',
      'USE LW3',
      'COMMIT',
      'BUY_DISTRICT 2 HILLS',
      'BUILD G02 3 1',
      'COMMIT',
      'USE LW1',
      'COMMIT',
      'USE LR2 Sh',
      'COMMIT',
      'BUILD G12 0 1',
      'USE G12 ShShShShShPtPtPt',
      'COMMIT',
      'FELL_TREES 1 0',
      'COMMIT',
      'FELL_TREES 2 2 Jo',
      'COMMIT',
      'USE LW2 Gn',
      'COMMIT',
      'BUILD F04 4 2',
      'USE F04 GnGnGnGnGnGnGn',
      'COMMIT',
      'BUILD F08 1 1',
      'USE F08 ClGnPnWo',
      'COMMIT',
      'BUY_PLOT 1 COAST',
      'BUILD F11 -1 1',
      'COMMIT',
      'BUY_DISTRICT 2 PLAINS',
      'CUT_PEAT 0 0',
      'COMMIT',
      'USE LW1',
      'COMMIT',
      'SETTLE SW1 2 2 PnSwSw',
      'COMMIT',
      'SETTLE SR2 1 2 BrPtWo',
      'COMMIT',
      'WORK_CONTRACT G12 Pn',
      'USE G12 ShFlFlFlFlFlFlCoSwSw',
      'COMMIT',
      'BUILD F17 3 2',
      'USE F17 Pn',
      'COMMIT',
      'USE LR2 Sh',
      'COMMIT',
      'USE LR3',
      'COMMIT',
      'BUY_DISTRICT 3 HILLS',
      'BUILD F14 3 3',
      'USE F14',
      'COMMIT',
      'BUILD F05 2 0',
      'COMMIT',
      'FELL_TREES 1 0',
      'COMMIT',
      'BUILD G19 1 0',
      'COMMIT',
      'USE LR2 Gn',
      'COMMIT',
      'CUT_PEAT 0 3',
      'COMMIT',
      'WORK_CONTRACT G07 Pn',
      'USE G07 PtPtPtPtPtPtPtPtPtPt',
      'COMMIT',
      'USE LW3',
      'COMMIT',
      'BUY_DISTRICT 3 HILLS',
      'BUILD G18 3 3',
      'USE G18 ClSnWoWo',
      'COMMIT',
      'USE LW1',
      'COMMIT',
      'USE F14 Jo',
      'COMMIT',
      'FELL_TREES 2 3',
      'COMMIT',
      'WORK_CONTRACT F04 Pn',
      'USE F04 GnGnGnGnGn',
      'COMMIT',
      'WORK_CONTRACT LR2 Pn',
      'WITH_LAYBROTHER',
      'USE LR2 JoSh',
      'COMMIT',
      'USE G18 ClClSnCo',
      'COMMIT',
      'FELL_TREES 2 3',
      'COMMIT',
      'WORK_CONTRACT F05 Pn',
      'WITH_LAYBROTHER',
      'USE F05 BrBrCoFlFlFlFlFl',
      'COMMIT',
      'SETTLE SR4 -1 2 BrBrShCo',
      'COMMIT',
      'SETTLE SW5 4 3 ShShFlWo',
      'COMMIT',
      'WORK_CONTRACT F17 Pn',
      'USE F17 PnPnPnBo',
      'COMMIT',
      'BUILD F21 2 2',
      'USE F21 GpGpGpGpGpGpGpGpGpWn',
      'COMMIT',
      'FELL_TREES 1 3',
      'COMMIT',
      'USE F17 PnPnBo',
      'COMMIT',
      'USE G18 ClClClWoWoWo',
      'COMMIT',
      'USE LR1',
      'COMMIT',
      'USE LR2 Gn',
      'COMMIT',
      'WORK_CONTRACT F04 Wn',
      'USE F04 GnGnGnGnGnGnGn',
      'COMMIT',
      'CUT_PEAT 0 3',
      'COMMIT',
      'USE G02 PtSwMt Cl',
      'COMMIT',
      'USE LW3',
      'COMMIT',
      'BUY_PLOT 0 MOUNTAIN',
      'BUILD G22 6 0',
      'USE G22',
      'COMMIT',
      'WORK_CONTRACT F05 Wn',
      'USE F05 BrBrCoFlFlFlFlFlFlFlWo',
      'COMMIT',
      'BUILD F24 4 2',
      'USE F24 BrBrWnWn',
      'COMMIT',
      'FELL_TREES 1 2',
      'COMMIT',
      'WORK_CONTRACT G22 PnPn',
      'USE G22',
      'COMMIT',
      'BUY_PLOT 1 COAST',
      'BUILD G26 -1 1',
      'USE G26 WoWo',
      'COMMIT',
      'USE LR2 Sh',
      'COMMIT',
      'WORK_CONTRACT G19 Wn',
      'USE G19 ShShShShShShShShShShSwSwSwSwSwSwSwSwSwSw',
      'COMMIT',
      'USE F24 BrBrWnWn',
      'COMMIT',
      'USE G18 ClClClSnPtPt',
      'COMMIT',
      'SETTLE SW6 2 3 NiPtPtPt',
      'COMMIT',
      'SETTLE SR6 3 2 MtCoCo',
      'COMMIT',
      'USE LW1',
      'COMMIT',
      'USE G18 ClClClWoWoWo',
      'COMMIT',
      'BUY_PLOT 2 MOUNTAIN',
      'BUILD G28 6 2',
      'USE G28',
      'SETTLE SR7 5 2 MtMtMtCoCoCo',
      'COMMIT',
      'USE F14',
      'COMMIT',
      'FELL_TREES 0 2',
      'COMMIT',
      'CUT_PEAT 0 1',
      'COMMIT',
      'USE G02 PnClBo Sh',
      'COMMIT',
      'WORK_CONTRACT G28 Wn',
      'WITH_LAYBROTHER',
      'USE G28',
      'SETTLE SW3 1 3 ShShShSh',
      'COMMIT',
      'USE LR1',
      'COMMIT',
      'BUY_PLOT 3 COAST',
      'BUILD F33 -1 3',
      'USE F33 BrCo',
      'COMMIT',
      'WORK_CONTRACT G26 Wn',
    ])

    const s1 = reduce<string[], GameState>((state, move) => reducer(state, move)!, s0, moves) as GameStatePlaying
    expect(s1).toBeDefined()
    expect(s1.frame.usableBuildings).toContain('G26')
    const c1 = control(s1, [])
    expect(c1.completion).toContain('WITH_LAYBROTHER')

    const s2 = reducer(s1, ['WITH_LAYBROTHER'])! as GameStatePlaying
    expect(s2).toBeDefined()
    // After WITH_LAYBROTHER, activePlayer should revert to Red (currentPlayer)
    expect(s2.frame.activePlayerIndex).toBe(s2.frame.currentPlayerIndex)
    // The Shipping Company should be marked as freely usable
    expect(s2.frame.usableBuildings).toContain('G26')

    const c2 = control(s2, [])
    // Red should be able to USE G26 (Shipping Company)
    expect(c2.completion).toContain('USE')

    const c2use = control(s2, ['USE'])
    expect(c2use.completion).toContain('G26')

    // Actually USE G26 (Shipping Company) to verify it works
    const s3 = reducer(s2, ['USE', 'G26'])! as GameStatePlaying
    expect(s3).toBeDefined()
  })
})
