import { reduce } from 'ramda'
import { control } from '..'
import { reducer } from '../reducer'
import { initialState } from '../state'
import { GameState, GameStatePlaying } from '../types'

const commands: string[] = [
  'CONFIG 1 france long',
  'START 23082 R G',
  'FELL_TREES 2 0',
  'COMMIT',
  'USE LR1',
  'COMMIT',
  'USE LR3',
  'COMMIT',
  'WORK_CONTRACT G13 Pn',
  'USE G13 PnPn',
  'COMMIT',
  'BUILD G02 3 1',
  'USE G02 ClSwWo Pt',
  'COMMIT',
  'CUT_PEAT 0 0',
  'COMMIT',
  'BUILD G07 0 0',
  'COMMIT',
  'USE G07 PtPtPtPtPtPtPtPtPtPt',
  'COMMIT',
  'WORK_CONTRACT LG2 Pn',
  'USE LG2 Gn',
  'COMMIT',
  'BUILD G06 2 0',
  'USE G06 CoCoCo',
  'BUY_DISTRICT 2 HILLS',
  'COMMIT',
  'BUILD G01 3 0',
  'COMMIT',
  'USE G01',
  'USE G06 CoCoCo',
  'COMMIT',
  'FELL_TREES 1 0',
  'COMMIT',
  'BUILD F03 3 2',
  'USE F03 Pn',
  'COMMIT',
  'BUY_DISTRICT 3 PLAINS',
  'USE LR1',
  'COMMIT',
  'BUILD F04 4 3',
  'COMMIT',
  'BUILD F09 4 2',
  'COMMIT',
  'USE F09',
  'USE F04 GnGnGnGnGnGnGn',
  'COMMIT',
  'BUILD F05 2 3',
  'USE F05 BrBrCoFlFlFlFlFlFlFlSw',
  'COMMIT',
  'BUILD G12 1 0',
  'COMMIT',
  'USE G12 BrBrCo',
  'COMMIT',
  'BUY_DISTRICT 4 PLAINS',
  'BUILD F08 3 4',
  'COMMIT',
  'BUILD F11 0 1',
  'WORK_CONTRACT F11 Pn',
  'USE F11',
  'SETTLE SR2 3 3 BrCo',
  'COMMIT',
  'WORK_CONTRACT LG2 Pn',
  'USE LG2 Sh',
  'COMMIT',
  'USE F09',
  'USE F03 Pn',
  'COMMIT',
  'USE F09',
  'USE F04 GnGnGnGnGnGnGn',
  'COMMIT',
  'CUT_PEAT 0 1',
  'COMMIT',
  'WORK_CONTRACT LG3 Pn',
  'USE LG3',
  'COMMIT',
  'BUILD G19 0 1',
  'USE G19 ShShShShShShShShShShSwSwSwSwSwSwSwSwSwSw',
  'COMMIT',
  'BUILD F15 1 4',
  'COMMIT',
  'USE G07 PtPtPtPtPtPtPtPt',
  'COMMIT',
  'BUILD G16 3 1',
  'BUILD F17 3 0',
  'BUILD G18 2 0',
  'WORK_CONTRACT F17 Pn',
  'USE F17 PnPnPnBo',
  'SETTLE SR3 2 4 MtPnPn',
  'COMMIT',
  'WORK_CONTRACT LG1 Pn',
  'USE LG1',
  'COMMIT',
  'USE F15 Pn',
  'COMMIT',
  'USE G12 MtMtCoCo',
  'COMMIT',
  'FELL_TREES 0 3',
  'COMMIT',
  'WORK_CONTRACT G13 Pn',
  'USE G13 PnPn',
  'COMMIT',
  'BUILD F21 0 3',
  'USE F21 GpGpGpGpGpWn',
  'COMMIT',
  'BUY_PLOT 2 MOUNTAIN',
  'BUILD F24 5 2',
  'USE F24 BrBrWnWn',
  'COMMIT',
  'USE G12 MtMtCoCo',
  'COMMIT',
  'USE F05 BrBrCoFlFlFlFlFlFlFlFlWo',
  'COMMIT',
  'BUY_DISTRICT 5 PLAINS',
  'BUILD F25 2 5',
  'COMMIT',
  'USE F09',
  'USE F24 BrBrWnWn',
  'COMMIT',
  'USE F24 BrBrWnWn',
  'COMMIT',
  'BUILD F20 1 0',
  'BUILD G22 1 1',
  'BUILD F23 4 1',
  'BUILD G26 1 1',
  'WORK_CONTRACT F23 PnPn',
  'USE F23 Pn',
  'SETTLE SR5 5 3 MtWo',
  'COMMIT',
  'USE F08 FlSnSwWo',
  'BUY_PLOT 3 COAST',
  'COMMIT',
  'USE LR1',
  'COMMIT',
  'BUILD F33 -1 4',
  'USE F33 WnCo',
  'COMMIT',
  'FELL_TREES 0 4',
  'COMMIT',
  'BUILD G28 4 5',
  'USE G28',
  'SETTLE SR6 3 5 MtCoCo',
  'COMMIT',
  'USE F09',
  'USE LR3',
  'COMMIT',
  'BUILD F27 0 1',
  'BUILD F30 4 0',
  'BUILD F32 3 0',
]

describe('game 504cc4e', () => {
  it('runs through moves', () => {
    const midState = reduce(
      (state: GameState, command: string) => {
        const newState = reducer(state, command.split(' '))!
        if (newState === undefined) console.log(command)
        return newState
      },
      initialState as GameState,
      commands
    ) as GameStatePlaying
    expect(midState).not.toBeUndefined()
    console.log(midState.players[0])
    console.log(control(midState, ['WORK_CONTRACT', 'F32']))
    const controls = control(midState, ['WORK_CONTRACT', 'F32'])
    expect(controls.completion).toStrictEqual(['PnPn'])
  })
})
