import { describe, it, expect } from '../testHelpers'
import { reducer } from '../reducer'
import { initialState } from '../state'
import { GameState, GameStatePlaying } from '../types'
import { control } from '../control'
import { map, reduce, split } from 'ramda'

describe('game Claude4-2', () => {
  it('F41 is not a valid building ID — USE F41 is rejected', () => {
    const s0 = initialState
    const moves: string[][] = map(split(' '), [
      'CONFIG 3 france long',
      'START 1699 R G B',
      'BUILD G07 3 1',
      'USE G07 Pt',
      'BUY_DISTRICT 2 HILLS',
      'COMMIT',
      'BUILD G12 3 1',
      'USE G12 ShPt',
      'COMMIT',
      'BUILD G01 3 1',
      'USE G01',
      'USE G07 Pt',
      'COMMIT',
      'USE LG3',
      'COMMIT',
      'FELL_TREES 1 0',
      'COMMIT',
      'USE LR3 Jo',
      'COMMIT',
      'USE LG1',
      'COMMIT',
      'USE LB2 Gn',
      'COMMIT',
      'BUILD F09 3 0',
      'COMMIT',
      'FELL_TREES 2 0',
      'COMMIT',
      'USE LB1',
      'COMMIT',
      'USE LR2 Sh',
      'COMMIT',
      'BUILD F04 4 2',
      'USE F04 Gn',
      'COMMIT',
      'USE G12 GnGnGnGnWoWo',
      'COMMIT',
      'USE LR3',
      'BUY_DISTRICT 2 PLAINS',
      'COMMIT',
      'USE LG3',
      'COMMIT',
      'BUILD F08 3 0',
      'USE F08 PnClWoSn',
      'BUY_DISTRICT 2 HILLS',
      'COMMIT',
      'USE LR2 Gn',
      'COMMIT',
      'CUT_PEAT 0 2',
      'COMMIT',
      'USE LB2 Sh',
      'BUY_PLOT -1 COAST',
      'COMMIT',
      'SETTLE SR2 2 2 ShPnCo',
      'COMMIT',
      'SETTLE SG1 3 2 ShCo',
      'COMMIT',
      'SETTLE SB3 -1 0 BrShSh',
      'COMMIT',
      'FELL_TREES 2 0 Jo',
      'COMMIT',
      'FELL_TREES 1 1',
      'COMMIT',
      'USE LB3',
      'COMMIT',
      'BUILD G02 2 0',
      'USE G02 PnShWo Gn',
      'COMMIT',
      'USE LG2 Sh',
      'COMMIT',
      'USE LB1',
      'COMMIT',
      'USE F09',
      'USE G01',
      'USE F04 GnGnGnGnGnGnGn',
      'COMMIT',
      'WORK_CONTRACT G02 Pn',
      'WITH_LAYBROTHER',
      'USE G02 ShFlCo Cl',
      'COMMIT',
      'USE LB2 Gn',
      'COMMIT',
      'CUT_PEAT 0 1',
      'COMMIT',
      'BUILD F05 3 0',
      'USE F05',
      'COMMIT',
      'FELL_TREES 2 0',
      'COMMIT',
      'WORK_CONTRACT F08 Pn',
      'WITH_LAYBROTHER',
      'USE F08 PnShSwWo',
      'COMMIT',
      'USE LG1',
      'COMMIT',
      'BUILD G18 4 2',
      'USE G18',
      'BUY_DISTRICT 3 HILLS',
      'COMMIT',
      'BUY_DISTRICT -1 HILLS',
      'BUILD F14 3 -1',
      'USE F14 Jo',
      'COMMIT',
      'BUILD G19 1 1',
      'COMMIT',
      'USE LB2 Sh',
      'COMMIT',
      'USE F09',
      'USE G02 GnPnSw Cl',
      'COMMIT',
      'USE LG2 Gn',
      'COMMIT',
      'COMMIT',
      'SETTLE SR3 4 2 BrShSh',
      'COMMIT',
      'SETTLE SG3 2 0 ShShGnGnGn',
      'COMMIT',
      'FELL_TREES 1 1',
      'COMMIT',
      'BUILD G16 3 2',
      'USE G16',
      'COMMIT',
      'USE LG2 Gn',
      'COMMIT',
      'USE G12 ShShWoWo',
      'COMMIT',
      'USE F14',
      'COMMIT',
      'USE LG1',
      'COMMIT',
      'USE LB1',
      'COMMIT',
      'BUILD F21 1 2',
      'COMMIT',
      'USE LG3',
      'BUY_DISTRICT 3 HILLS',
      'COMMIT',
      'CUT_PEAT 0 2',
      'COMMIT',
      'USE F09',
      'USE F14 Jo',
      'COMMIT',
      'FELL_TREES 1 3',
      'COMMIT',
      'USE G12 ShShShPtPtPt',
      'COMMIT',
      'WORK_CONTRACT F05 PnPn',
      'WITH_LAYBROTHER',
      'USE F05 BrBrCoFlFlFlFlFlFl',
      'BUY_DISTRICT 3 PLAINS',
      'COMMIT',
      'USE F04 GnGn',
      'BUY_PLOT 3 MOUNTAIN',
      'COMMIT',
      'FELL_TREES 1 2',
      'COMMIT',
      'SETTLE SR5 3 3 BrShWo',
      'COMMIT',
      'SETTLE SG2 4 3 FlFlPnPtPt',
      'COMMIT',
      'SETTLE SB2 2 0 GnGnGnPtPt',
      'COMMIT',
      'USE F21 GpGpGpGpGpGpGpGpGpGpGpGpGpGpGpGpGpWn',
      'COMMIT',
      'FELL_TREES 1 0',
      'COMMIT',
      'FELL_TREES 1 3',
      'COMMIT',
      'BUY_PLOT 0 MOUNTAIN',
      'BUILD G22 6 0',
      'USE G22',
      'COMMIT',
      'USE LG3',
      'COMMIT',
      'FELL_TREES 2 2',
      'COMMIT',
      'FELL_TREES 2 -1 Jo',
      'COMMIT',
      'WORK_CONTRACT G22 PnPn',
      'WITH_LAYBROTHER',
      'USE G22',
      'COMMIT',
      'BUILD G28 3 3',
      'USE G28',
      'SETTLE SB1 3 2 GnPt',
      'COMMIT',
      'USE LR2 Sh',
      'COMMIT',
      'USE LG3',
      'COMMIT',
      'CUT_PEAT 0 3',
      'COMMIT',
      'BUY_PLOT 2 MOUNTAIN',
      'BUILD F32 5 1',
      'CONVERT Wn',
      'USE F32 Pn',
      'CUT_PEAT 0 0 Jo',
      'FELL_TREES 1 1',
      'COMMIT',
      'USE LG2 Gn',
      'COMMIT',
      'USE LB3',
      'COMMIT',
      'WORK_CONTRACT G19 Wn',
      'CONVERT GnGnGnGn',
      'USE G19 ShShShShShShSwSwSwSwSwSw',
      'COMMIT',
      'USE F04 GnGnGnGnGnGnGn',
      'COMMIT',
      'USE G18 ClClClPtPt',
      'COMMIT',
      'USE F09',
      'USE G01',
      'USE G28',
      'SETTLE SR7 4 3 MtMtMtPtPtPtPtWo',
      'COMMIT',
      'USE F05 FlFlFlFlFlFlFlPtPt',
      'COMMIT',
      'COMMIT',
      'SETTLE SR6 5 3 MtPtPtPt',
      'COMMIT',
      'SETTLE SG5 3 3 BrBrPt',
      'COMMIT',
      'USE G28',
      'COMMIT',
      'USE LR1',
      'COMMIT',
      'WORK_CONTRACT G12 PnPn',
      'WITH_LAYBROTHER',
      'USE G12 BrBrBrWoWoWoWo',
      'COMMIT',
      'USE G18 ClClPt',
      'COMMIT',
      'BUILD F24 5 2',
      'USE F24 BrBrWnWn',
      'COMMIT',
      'USE LG3',
      'COMMIT',
      'USE G28',
      'COMMIT',
      'WORK_CONTRACT LB2 Wn',
      'WITH_LAYBROTHER',
      'USE LB2 Gn',
      'COMMIT',
      'CUT_PEAT 0 3',
      'COMMIT',
      'USE F08 PtPnClCe',
      'COMMIT',
      'BUILD F40 5 0',
      'USE F40',
      'USE F20 MtBrWn',
      'COMMIT',
      'WITH_PRIOR',
      'USE LG2 Gn',
      'COMMIT',
      'USE G28',
      'SETTLE SB5 4 3 NiPt',
      'COMMIT',
      'USE F09',
      'USE G01',
      'USE F40',
      'USE G41 Ni OrOrCeCeBo',
      'COMMIT',
      'FELL_TREES 2 3',
      'COMMIT',
      'USE F08 PnClCeBr',
      'COMMIT',
      'USE G01',
      'USE F40',
      'USE G34 BoCeOrRq',
      'COMMIT',
      'USE LG1',
      'COMMIT',
      'USE G28',
      'COMMIT',
      'BUILD F20 2 3',
      'COMMIT',
    ])

    const sN = reduce<string[], GameState>((state, move) => reducer(state, move)!, s0, moves) as GameStatePlaying
    expect(sN).toBeDefined()

    const cTop = control(sN, [])
    expect(cTop.completion).toContain('USE')

    // F41 does not exist as a building ID in Ora et Labora (IDs skip from F40 Hospice to G41 HouseOfTheBrotherhood).
    const cUse = control(sN, ['USE'])
    expect(cUse.completion).not.toContain('F41')
    expect(cUse.completion).toStrictEqual([
      'G01',
      'G02',
      'F04',
      'F05',
      'G07',
      'F08',
      'F09',
      'G12',
      'F14',
      'G16',
      'G18',
      'G19',
      'F20',
      'F21',
      'G22',
      'F24',
      'G28',
      'F32',
      'F40',
      'LB1',
      'LB2',
      'LB3',
      'LG1',
      'LG2',
      'LG3',
      'LR1',
      'LR2',
      'LR3',
    ])

    const cF41 = control(sN, ['USE', 'F41'])
    expect(cF41.completion).toStrictEqual([])

    expect(() => reducer(sN, ['USE', 'F41'])).toThrow()
  })
})
