import { describe, it, expect } from '../testHelpers'
import { reducer } from '../reducer'
import { initialState } from '../state'
import { GameState } from '../types'
import { control } from '../control'
import { map, reduce, split } from 'ramda'

describe('instance 2952eea3-1e7b-4827-8a9f-9302a38931ad', () => {
  it('allows USE F10 (Carpentry) with no parameters to drop a clergy without felling a tree', () => {
    const s0 = initialState
    const moves: string[][] = map(split(' '), [
      'CONFIG 4 france long',
      'START 74239 R G W B',
      'BUILD G12 3 0',
      'USE G12 ShPt',
      'COMMIT',
      'BUILD G07 3 0',
      'USE G07 Pt',
      'COMMIT',
      'BUILD G01 3 1',
      'USE G01',
      'USE G07 Pt',
      'COMMIT',
      'FELL_TREES 1 0',
      'COMMIT',
      'USE LG2 Gn',
      'COMMIT',
      'USE LW3',
      'BUY_PLOT -1 COAST',
      'COMMIT',
      'USE LR1',
      'COMMIT',
      'BUILD G02 3 1',
      'USE G02 PnClSh Wo',
      'COMMIT',
      'CUT_PEAT 0 0',
      'COMMIT',
      'FELL_TREES 1 0',
      'COMMIT',
      'BUY_DISTRICT 2 PLAINS',
      'BUILD G13 1 2',
      'COMMIT',
      'USE LB3',
      'COMMIT',
      'USE LG1',
      'COMMIT',
      'USE LW2 Gn',
      'COMMIT',
      'USE LR3 Jo',
      'COMMIT',
      'USE LB2 Sh',
      'COMMIT',
      'USE G12 GnGnGnPtPtPt',
      'COMMIT',
      'WORK_CONTRACT G13 Pn',
      'WITH_LAYBROTHER',
      'USE G13',
      'COMMIT',
      'BUILD F09 3 2',
      'USE F09',
      'USE G01',
      'USE G02 GnPnSh Wo',
      'COMMIT',
      'WORK_CONTRACT LG1 Pn',
      'WITH_LAYBROTHER',
      'USE LG1',
      'COMMIT',
      'BUILD F08 0 0',
      'COMMIT',
      'USE LW1',
      'COMMIT',
      'BUILD F10 2 2',
      'COMMIT',
      'USE G02 PtPnSh Cl',
      'COMMIT',
      'USE LG3',
      'BUY_PLOT -1 COAST',
      'COMMIT',
      'BUILD F04 -1 0',
      'USE F04 GnGnGnGn',
      'COMMIT',
      'USE LR2 Gn',
      'COMMIT',
      'USE LB3',
      'COMMIT',
      'FELL_TREES 1 0',
      'COMMIT',
      'CUT_PEAT 0 1',
      'COMMIT',
      'SETTLE SR1 3 0 GnWo',
      'COMMIT',
      'SETTLE SB2 3 0 ShShWoWoWo',
      'COMMIT',
      'SETTLE SG1 -1 0 PnWo',
      'COMMIT',
      'SETTLE SW1 -1 -1 FlCo',
      'COMMIT',
      'USE LR2 GnJo',
      'COMMIT',
      'USE G02 GnShWo Pn',
      'BUY_DISTRICT 2 HILLS',
      'COMMIT',
      'FELL_TREES 2 0',
      'COMMIT',
      'USE LW2 Sh',
      'COMMIT',
      'USE F09',
      'USE G01',
      'USE F04 GnGnGnGnGnGnGn',
      'COMMIT',
      'BUILD G18 3 2',
      'COMMIT',
      'USE LG2 Gn',
      'COMMIT',
      'USE LW1',
      'COMMIT',
      'WORK_CONTRACT F08 Pn',
      'WITH_LAYBROTHER',
      'USE F08 FlGnSwWo',
      'BUY_DISTRICT 3 HILLS',
      'COMMIT',
      'CUT_PEAT 0 2',
      'COMMIT',
      'USE G12 GnGnGnPnWoWo',
      'COMMIT',
      'BUILD F05 1 0',
      'USE F05 FlFlFlPtBrBr',
      'COMMIT',
      'BUILD F14 3 3',
      'USE F14 Jo',
      'COMMIT',
      'USE G18 ClClClPtPt',
      'COMMIT',
      'FELL_TREES 1 1',
      'COMMIT',
      'SETTLE SW2 3 1 ShShCo',
      'COMMIT',
      'SETTLE SR2 4 3 BrCo',
      'COMMIT',
      'SETTLE SB3 4 2 ShPnPnPnPnPn',
      'COMMIT',
      'COMMIT',
      'USE LW1',
      'COMMIT',
      'USE G13 PnPn',
      'COMMIT',
      'USE G02 PtClCe Gn',
      'COMMIT',
      'BUILD F11 -1 -1',
      'USE F11',
      'COMMIT',
      'WORK_CONTRACT G12 Pn',
      'USE G12 ShShShNiPtPtPt',
      'COMMIT',
      'USE F09',
      'USE F10 2 3',
      'BUILD F23 4 2',
      'USE F23 Pn',
      'COMMIT',
      'FELL_TREES 2 2',
      'COMMIT',
      'USE LG2 Gn',
      'COMMIT',
      'BUILD F21 0 1',
      'COMMIT',
      'USE F09',
      'USE G01',
      'USE F11',
      'COMMIT',
      'USE G18 ClClClWoWoWo',
      'COMMIT',
      'BUILD F25 1 0',
      'COMMIT',
      'USE LW3',
      'BUY_DISTRICT 2 PLAINS',
      'COMMIT',
      'WORK_CONTRACT F21 Wn',
      'WITH_LAYBROTHER',
      'USE F21 GpGpGpGpGpGpGpWn',
      'BUY_DISTRICT 4 HILLS',
      'COMMIT',
      'FELL_TREES 1 2',
      'COMMIT',
      'USE G12 GnGnGnGnWoWoWo',
      'COMMIT',
      'USE LW1',
      'COMMIT',
      'CUT_PEAT 0 3',
      'COMMIT',
      'USE G02 CeGnWo Pn',
      'COMMIT',
      'USE LG3',
      'COMMIT',
      'BUILD F24 4 2',
      'COMMIT',
      'WORK_CONTRACT F05 Wn',
      'WITH_LAYBROTHER',
      'USE F05 BrBrCoFlFlFlFlFlFl',
      'COMMIT',
      'WORK_CONTRACT G13 PnPn',
      'WITH_PRIOR',
      'USE G13',
      'COMMIT',
      'USE LG1',
      'COMMIT',
      'WORK_CONTRACT F14 PnPn',
      'USE F14',
      'COMMIT',
      'USE F09',
      'USE F10 2 4',
      'BUY_PLOT 0 MOUNTAIN',
      'BUILD G22 6 0',
      'USE G22 Jo',
      'COMMIT',
      'USE G02 GnClWo Pn',
      'COMMIT',
      'USE LG1',
      'COMMIT',
      'USE F21 GpGpGpGpGpGpGp',
      'COMMIT',
    ])

    const s1 = reduce<string[], GameState>((state, move) => reducer(state, move)!, s0, moves)
    expect(s1).toBeDefined()

    const c1 = control(s1, ['USE', 'F10'])
    expect(c1.completion).toContain('')

    const s2 = reducer(s1, ['USE', 'F10'])
    expect(s2).toBeDefined()
  })
})
