name: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  APP_NAME: hathora-et-labora

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g hathora
      - run: hathora cloud deploy --appName $APP_NAME --token ${{ secrets.HATHORA_TOKEN }}
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm install hathora -g
      - run: APP_SECRET=${{ secrets.HATHORA_APP_SECRET }} hathora build --only client
      - run: echo '/* /index.html 200' > client/web/dist/_redirects;
      - run: |
          npx netlify deploy --prod \
          --site '${{ secrets.NETLIFY_SITE_ID }}' \
          --auth '${{ secrets.NETLIFY_AUTH_TOKEN }}' \
          --dir=client/web/dist;
