name: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  APP_NAME: hathora-et-labora
  APP_ID: app-c90ca9cf-ab67-42e0-ae7d-ada07e5616fd

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install -g hathora
      - run: hathora cloud deploy --appName $APP_NAME --token ${{ secrets.HATHORA_TOKEN }}
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm install hathora -g
      - run: APP_SECRET=${{ secrets.HATHORA_APP_SECRET }} hathora build --only client
      - run: echo '/* /index.html 200' > client/web/dist/_redirects;
      - uses: jsmrcaga/action-netlify-deploy@v1.6.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Prod deploy ${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: client/web/dist
