name: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  APP_NAME: hathora-et-labora
  APP_ID: app-c90ca9cf-ab67-42e0-ae7d-ada07e5616fd

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install -g hathora
      - run: hathora cloud deploy --appName $APP_NAME --token ${{ secrets.HATHORA_TOKEN }}
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm install hathora -g
      - run: npm install --global vercel@latest
      - run: APP_SECRET=${{ secrets.HATHORA_APP_SECRET }} hathora build --only client
      - run: echo '/* /index.html 200' > client/web/dist/_redirects;
      - run: npm install --global vercel@canary
      - run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
