name: game

on:
  workflow_dispatch:
  pull_request:
    paths:
      - game/**
      - .github/workflows/game.yml
  push:
    branches:
      - main

env:
  CI: true

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: game
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
        with:
          package_json_file: game/package.json
      - uses: actions/setup-node@v6
        with:
          node-version: latest
      - name: Get pnpm store directory
        id: pnpm-store
        run: echo "path=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"
      - name: Cache pnpm store
        uses: actions/cache@v5
        with:
          path: ${{ steps.pnpm-store.outputs.path }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('game/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
      - run: pnpm run build
      - run: pnpm run test
