name: game

on:
  workflow_dispatch:
  pull_request:
    paths:
      - game/**
      - .github/workflows/game.yml
  push:
    branches:
      - main

env:
  CI: true

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: game
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: game/package.json
      - uses: actions/setup-node@v6
        with:
          node-version: latest
          package-manager-cache: false
      - run: pnpm install --frozen-lockfile --allow-build=esbuild
      - run: pnpm run lint
      - run: pnpm run build --if-present
      - run: pnpm run test
