name: publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: game
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
        with:
          package_json_file: game/package.json
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
          package-manager-cache: false # cache injection is a fun attack to debug
      - run: pnpm install
      - run: pnpm run lint
      - run: pnpm run build
      - run: pnpm stage publish --provenance --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
